/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/video/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Video */
        post: operations["upload_video_api_video_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/video/{video_id}/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Video Meta */
        get: operations["video_meta_api_video__video_id__meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/video/{video_id}/frame/{frame_n}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Frame */
        get: operations["get_frame_api_video__video_id__frame__frame_n__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/video/{video_id}/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Thumbnail */
        get: operations["get_thumbnail_api_video__video_id__thumbnail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calibrate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calibrate */
        post: operations["calibrate_api_calibrate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/video/{video_id}/plan-view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Plan View
         * @description Kuş bakışı (kalibre edilmiş yol düzleminin projeksiyonu) — Adım 4 canlı önizleme.
         *
         *     Gerçek bir havadan fotoğraf değildir; yalnızca kontrol noktalarının kapladığı
         *     dünya bölgesi güvenilirdir (bkz. docs/dtp-expert-karsilastirma.md §5).
         */
        post: operations["plan_view_api_video__video_id__plan_view_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/video/{video_id}/autoref": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autoref */
        post: operations["autoref_api_video__video_id__autoref_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Pipeline */
        post: operations["start_pipeline_api_pipeline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job/{job_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Status */
        get: operations["job_status_api_job__job_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job/{job_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Report */
        get: operations["download_report_api_job__job_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job/{job_id}/overlay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Overlay
         * @description Tarayıcı içi oynatma — inline Content-Disposition.
         */
        get: operations["stream_overlay_api_job__job_id__overlay_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job/{job_id}/overlay/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Overlay
         * @description İndirme — attachment Content-Disposition.
         */
        get: operations["download_overlay_api_job__job_id__overlay_download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job/{job_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Results */
        get: operations["job_results_api_job__job_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job/{job_id}/track/{track_id}/axle-suggest-frame": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Axle Suggest Frame */
        get: operations["axle_suggest_frame_api_job__job_id__track__track_id__axle_suggest_frame_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job/{job_id}/track/{track_id}/axle-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Axle Check */
        post: operations["axle_check_api_job__job_id__track__track_id__axle_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job/{job_id}/recalibrate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recalibrate
         * @description Aks doğrulamasını kalibrasyona ekleyip mevcut track'lerle (tespit tekrarlanmadan)
         *     yeni bir job olarak hızlıca yeniden analiz eder. Eski job/rapor değişmeden kalır —
         *     forensic bütünlük için her analiz sonucu kendi kalibrasyonuyla sabittir.
         */
        post: operations["recalibrate_api_job__job_id__recalibrate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AutoRefRequest */
        AutoRefRequest: {
            /** Frame N */
            frame_n: number;
            /**
             * Lane Width M
             * @default 3.5
             */
            lane_width_m: number;
            /**
             * Dash Length M
             * @default 3
             */
            dash_length_m: number;
            /**
             * D Near M
             * @default 5
             */
            d_near_m: number;
        };
        /** AxleCheckRequest */
        AxleCheckRequest: {
            /** Pixel Left */
            pixel_left: [
                number,
                number
            ];
            /** Pixel Right */
            pixel_right: [
                number,
                number
            ];
            /** Known Width M */
            known_width_m: number;
        };
        /** AxleCheckResponse */
        AxleCheckResponse: {
            /** Measured M */
            measured_m: number;
            /** Known M */
            known_m: number;
            /** Error Pct */
            error_pct: number;
        };
        /** AxleSuggestFrameResponse */
        AxleSuggestFrameResponse: {
            /** Frame N */
            frame_n?: number | null;
        };
        /** Body_upload_video_api_video_upload_post */
        Body_upload_video_api_video_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** CalibrateRequest */
        CalibrateRequest: {
            /** Video Id */
            video_id: string;
            /** Frame N */
            frame_n: number;
            /** Control Points */
            control_points: components["schemas"]["ControlPointIn"][];
        };
        /** CalibrateResponse */
        CalibrateResponse: {
            /** Rms M */
            rms_m: number;
            /** Inlier Count */
            inlier_count: number;
            /** Confidence Layer */
            confidence_layer: string;
            /** Homography */
            homography: number[][];
            /** Planarity Warning */
            planarity_warning: boolean;
            /**
             * Point Count
             * @default 0
             */
            point_count: number;
            /** Loo Rms M */
            loo_rms_m?: number | null;
            /**
             * Holdout Rows
             * @default []
             */
            holdout_rows: {
                [key: string]: unknown;
            }[];
            /**
             * Rejected Points
             * @default []
             */
            rejected_points: {
                id: string;
                error_cm: number;
                threshold_cm: number;
            }[];
        };
        /** ControlPointIn */
        ControlPointIn: {
            /** Id */
            id: string;
            /** Pixel */
            pixel: [
                number,
                number
            ];
            /** World M */
            world_m: [
                number,
                number
            ];
            /**
             * Source
             * @default operator
             * @enum {string}
             */
            source: "operator" | "site_measurement" | "auto";
            /**
             * Held Out
             * @default false
             */
            held_out: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobResultOut */
        JobResultOut: {
            /** Job Id */
            job_id: string;
            /** Vehicle Count */
            vehicle_count: number;
            /** Estimates */
            estimates: components["schemas"]["SpeedEstimateOut"][];
        };
        /** JobStatusOut */
        JobStatusOut: {
            /** Job Id */
            job_id: string;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "done" | "error";
            /** Progress Pct */
            progress_pct: number;
            /** Eta S */
            eta_s?: number | null;
            /** Error */
            error?: string | null;
        };
        /** PipelineRequest */
        PipelineRequest: {
            /** Video Id */
            video_id: string;
            calibration: components["schemas"]["CalibrateResponse"];
            /** Control Points */
            control_points: components["schemas"]["ControlPointIn"][];
            /** Fps Override */
            fps_override?: number | null;
            /**
             * Frame Step
             * @default 1
             */
            frame_step: number;
            /**
             * Model Size
             * @default nano
             * @enum {string}
             */
            model_size: "nano" | "small" | "medium";
        };
        /** PlanViewRequest */
        PlanViewRequest: {
            /** Frame N */
            frame_n: number;
            /** Control Points */
            control_points: components["schemas"]["ControlPointIn"][];
        };
        /** ProposedPointOut */
        ProposedPointOut: {
            /** Pixel */
            pixel: [
                number,
                number
            ];
            /** World M */
            world_m: [
                number,
                number
            ];
            /** Detection Confidence */
            detection_confidence: number;
            /** Description */
            description: string;
        };
        /** RecalibrateRequest */
        RecalibrateRequest: {
            /** Video Id */
            video_id: string;
            /** Control Points */
            control_points: components["schemas"]["ControlPointIn"][];
            /** Track Id */
            track_id: number;
            /** Pixel Left */
            pixel_left: [
                number,
                number
            ];
            /** Pixel Right */
            pixel_right: [
                number,
                number
            ];
            /** Known Width M */
            known_width_m: number;
        };
        /** SpeedEstimateOut */
        SpeedEstimateOut: {
            /** Track Id */
            track_id: number;
            /** Vehicle Class */
            vehicle_class: string;
            /** Speed Kmh */
            speed_kmh: number;
            /** Ci Kmh */
            ci_kmh: number;
            /** Confidence Level */
            confidence_level: string;
            /** Frame Count */
            frame_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VideoMetaOut */
        VideoMetaOut: {
            /** Video Id */
            video_id: string;
            /** Fps */
            fps: number;
            /** Fps Source */
            fps_source: string;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Frame Count */
            frame_count: number;
            /** Sha256 */
            sha256: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_video_api_video_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_video_api_video_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoMetaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    video_meta_api_video__video_id__meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoMetaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_frame_api_video__video_id__frame__frame_n__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
                frame_n: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_thumbnail_api_video__video_id__thumbnail_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calibrate_api_calibrate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalibrateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_view_api_video__video_id__plan_view_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanViewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    autoref_api_video__video_id__autoref_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutoRefRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposedPointOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_pipeline_api_pipeline_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_status_api_job__job_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_report_api_job__job_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_overlay_api_job__job_id__overlay_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_overlay_api_job__job_id__overlay_download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_results_api_job__job_id__results_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    axle_suggest_frame_api_job__job_id__track__track_id__axle_suggest_frame_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                track_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AxleSuggestFrameResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    axle_check_api_job__job_id__track__track_id__axle_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                track_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AxleCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AxleCheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recalibrate_api_job__job_id__recalibrate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecalibrateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
